import 'package:flutter/material.dart';
import 'er_widgets.dart';

/// Displayed after each of the first 3 rooms completes.
///
/// If the room passed it shows the unlocked 4-character code and highlights
/// which character from this room contributes to the FINAL PUZZLE.
class RoomSummaryScreen extends StatelessWidget {
  final String roomName;
  final int correct;
  final int total;

  /// The random 4-char code generated by [EscapeRoomProvider.completeRoom].
  /// Empty string or null when the room was failed.
  final String? code;

  /// Which position (0-indexed) of this room's code feeds into the
  /// final 4-character puzzle code.
  ///
  ///  Room 1 → contributes position 0 (1st character)
  ///  Room 2 → contributes position 1 (2nd character)
  ///  Room 3 → contributes position 2 (3rd character)
  ///  Room 4 → contributes position 3 (4th character)
  final int codeContributionIndex;

  final bool isPassed;
  final VoidCallback onRetry;
  final VoidCallback onNext;

  const RoomSummaryScreen({
    super.key,
    required this.roomName,
    required this.correct,
    required this.total,
    this.code,
    required this.codeContributionIndex,
    required this.isPassed,
    required this.onRetry,
    required this.onNext,
  });

  @override
  Widget build(BuildContext context) {
    final double pct = total > 0 ? correct / total : 0;
    final int pctInt = (pct * 100).round();

    String message;
    if (pct >= 1.0) {
      message = '🏆 PERFECT SCORE! Absolutely incredible!';
    } else if (pct >= 0.9) {
      message = '🌟 Amazing work! Almost perfect!';
    } else if (pct >= 0.8) {
      message = '🎉 Great job! You really know your English!';
    } else if (pct >= 0.7) {
      message = '🚀 You passed this room! Keep it up!';
    } else if (pct >= 0.6) {
      message = '💪 So close! Just a little more practice.';
    } else if (pct >= 0.5) {
      message = '📚 Keep studying! You\'re on the right track.';
    } else {
      message = '🔥 Don\'t give up! Review and try again.';
    }

    final color = isPassed ? ERColors.green : ERColors.orange;

    return ERScaffold(
      topColor: const Color(0xFF100A20),
      botColor: const Color(0xFF1A1040),
      roomLabel: '📊 Result: $roomName',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const SizedBox(height: 20),

          // ── Score circle ──────────────────────────────────────────
          Center(
            child: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: color.withValues(alpha: 0.2),
                border: Border.all(color: color, width: 4),
                boxShadow: [
                  BoxShadow(
                      color: color.withValues(alpha: 0.4),
                      blurRadius: 20,
                      spreadRadius: 5),
                ],
              ),
              child: Text(
                '$pctInt%',
                style: TextStyle(
                    color: color, fontSize: 40, fontWeight: FontWeight.w900),
              ),
            ),
          ),
          const SizedBox(height: 20),

          Text(
            '$correct / $total Correct',
            textAlign: TextAlign.center,
            style: const TextStyle(
                color: Colors.white, fontSize: 20, fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 24),

          // ── Message ───────────────────────────────────────────────
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.white.withValues(alpha: 0.2)),
            ),
            child: Text(
              message,
              textAlign: TextAlign.center,
              style:
                  const TextStyle(color: Colors.white, fontSize: 16, height: 1.5),
            ),
          ),
          const SizedBox(height: 24),

          // ── Code display (only when passed and code exists) ───────
          if (isPassed && code != null && code!.isNotEmpty) ...[
            _CodeDisplay(
              code: code!,
              contributionIndex: codeContributionIndex,
              roomName: roomName,
            ),
            const SizedBox(height: 32),
          ],

          // ── Action button ─────────────────────────────────────────
          if (isPassed)
            ERNextButton(
              label: 'Proceed to Next Room  →',
              onTap: onNext,
              color: ERColors.green,
            )
          else
            ERNextButton(
              label: '↻ Retry Room',
              onTap: onRetry,
              color: ERColors.orange,
            ),
        ],
      ),
    );
  }
}

// ══════════════════════════════════════════════════════════════════
// CODE DISPLAY WIDGET
// Renders the 4 code characters individually, highlighting the one
// character that contributes to the FINAL PUZZLE.
// ══════════════════════════════════════════════════════════════════
class _CodeDisplay extends StatelessWidget {
  final String code;
  final int contributionIndex;
  final String roomName;

  const _CodeDisplay({
    required this.code,
    required this.contributionIndex,
    required this.roomName,
  });

  @override
  Widget build(BuildContext context) {
    final chars = code.split('');
    final ordinals = ['1st', '2nd', '3rd', '4th'];
    final contributionChar =
        contributionIndex < chars.length ? chars[contributionIndex] : '?';

    return Column(
      children: [
        // Header
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('🔑', style: TextStyle(fontSize: 18)),
            const SizedBox(width: 8),
            const Text(
              'Room Code Unlocked!',
              style: TextStyle(
                  color: Colors.white70,
                  fontSize: 14,
                  fontWeight: FontWeight.w700),
            ),
          ],
        ),
        const SizedBox(height: 12),

        // 4-character code blocks
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: List.generate(chars.length, (i) {
            final isHighlighted = i == contributionIndex;
            return _CodeCharBox(
              char: chars[i],
              position: i + 1,
              isHighlighted: isHighlighted,
            );
          }),
        ),
        const SizedBox(height: 14),

        // Explanation banner
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
          decoration: BoxDecoration(
            color: ERColors.accent.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(14),
            border: Border.all(color: ERColors.accent.withValues(alpha: 0.5)),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text('💡', style: TextStyle(fontSize: 16)),
              const SizedBox(width: 8),
              Flexible(
                child: RichText(
                  textAlign: TextAlign.center,
                  text: TextSpan(
                    style: const TextStyle(fontSize: 13, color: Colors.white70),
                    children: [
                      TextSpan(
                        text: '"$contributionChar"',
                        style: const TextStyle(
                          color: ERColors.accent,
                          fontWeight: FontWeight.w900,
                          fontSize: 15,
                        ),
                      ),
                      TextSpan(
                        text:
                            ' (the ${ordinals[contributionIndex]} character) goes into your FINAL CODE',
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

// ── Single code character box ──────────────────────────────────────
class _CodeCharBox extends StatelessWidget {
  final String char;
  final int position;
  final bool isHighlighted;

  const _CodeCharBox({
    required this.char,
    required this.position,
    required this.isHighlighted,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 5),
      child: Column(
        children: [
          // Position label
          Text(
            '#$position',
            style: TextStyle(
              color: isHighlighted
                  ? ERColors.accent
                  : Colors.white.withValues(alpha: 0.4),
              fontSize: 10,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 4),
          // Character box
          AnimatedContainer(
            duration: const Duration(milliseconds: 300),
            width: 56,
            height: 64,
            decoration: BoxDecoration(
              color: isHighlighted
                  ? ERColors.accent.withValues(alpha: 0.25)
                  : Colors.white.withValues(alpha: 0.08),
              borderRadius: BorderRadius.circular(14),
              border: Border.all(
                color: isHighlighted ? ERColors.accent : Colors.white.withValues(alpha: 0.3),
                width: isHighlighted ? 2.5 : 1.5,
              ),
              boxShadow: isHighlighted
                  ? [
                      BoxShadow(
                        color: ERColors.accent.withValues(alpha: 0.4),
                        blurRadius: 14,
                        spreadRadius: 2,
                      )
                    ]
                  : [],
            ),
            alignment: Alignment.center,
            child: Text(
              char,
              style: TextStyle(
                color: isHighlighted ? ERColors.accent : Colors.white,
                fontSize: 28,
                fontWeight: FontWeight.w900,
                letterSpacing: 0,
              ),
            ),
          ),
          if (isHighlighted) ...[
            const SizedBox(height: 4),
            const Text(
              '⬆ USE',
              style: TextStyle(
                  color: ERColors.accent,
                  fontSize: 9,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1),
            ),
          ],
        ],
      ),
    );
  }
}
